package com.example.celltracker
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.hardware.display.DisplayManager;import android.media.MediaRecorder;import android.media.projection.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.util.DisplayMetrics;import android.view.WindowManager;import androidx.core.app.NotificationCompat
class TestScreenRecordingService:Service(){
 private var p:MediaProjection?=null;private var r:MediaRecorder?=null;private var d:android.hardware.display.VirtualDisplay?=null;private var u:Uri?=null
 override fun onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel(CH,"Test screen recording",NotificationManager.IMPORTANCE_LOW))}
 override fun onBind(i:Intent?)=null
 override fun onStartCommand(i:Intent?,f:Int,id:Int):Int{when(i?.action){START->start(i);STOP->stopRec()};return START_NOT_STICKY}
 private fun start(i:Intent){if(isRecording)return;val code=i.getIntExtra(CODE,Activity.RESULT_CANCELED);@Suppress("DEPRECATION") val data:Intent?=if(Build.VERSION.SDK_INT>=33)i.getParcelableExtra(DATA,Intent::class.java) else i.getParcelableExtra(DATA);if(code!=Activity.RESULT_OK||data==null){stopSelf();return}
  val now=System.currentTimeMillis();val name=safe(i.getStringExtra(NAME).orEmpty().ifBlank{"CellTracker_Test"})+"_"+java.text.SimpleDateFormat("yyyyMMdd_HHmmss",java.util.Locale.US).format(java.util.Date(now))+".mp4";val values=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,name);put(MediaStore.Downloads.MIME_TYPE,"video/mp4");if(Build.VERSION.SDK_INT>=29){put(MediaStore.Downloads.RELATIVE_PATH,ReportStorage.relativePath("Screen Recordings",now));put(MediaStore.Downloads.IS_PENDING,1)}};u=contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values);val fd=u?.let{contentResolver.openFileDescriptor(it,"w")?.fileDescriptor}?:return
  val m=DisplayMetrics();@Suppress("DEPRECATION")(getSystemService(WINDOW_SERVICE) as WindowManager).defaultDisplay.getRealMetrics(m);val w=(m.widthPixels/2)*2;val h=(m.heightPixels/2)*2
  r=if(Build.VERSION.SDK_INT>=31)MediaRecorder(this) else @Suppress("DEPRECATION") MediaRecorder();r!!.apply{setVideoSource(MediaRecorder.VideoSource.SURFACE);setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);setVideoEncoder(MediaRecorder.VideoEncoder.H264);setVideoSize(w,h);setVideoFrameRate(30);setVideoEncodingBitRate(8_000_000);setOutputFile(fd);prepare()}
  val n=NotificationCompat.Builder(this,CH).setSmallIcon(android.R.drawable.presence_video_online).setContentTitle("CellTracker screen recording").setContentText(name).setOngoing(true).build();if(Build.VERSION.SDK_INT>=29)startForeground(NID,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION) else startForeground(NID,n)
  p=getSystemService(MediaProjectionManager::class.java).getMediaProjection(code,data);p?.registerCallback(object:MediaProjection.Callback(){override fun onStop(){stopRec()}},Handler(mainLooper));d=p?.createVirtualDisplay("CellTrackerTestRecording",w,h,m.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,r!!.surface,null,null);r!!.start();isRecording=true;currentName=name;currentUri=u.toString();currentStartedAt=System.currentTimeMillis()
 }
 private fun stopRec(){if(!isRecording){stopSelf();return};isRecording=false;runCatching{r?.stop()};runCatching{r?.release()};r=null;runCatching{d?.release()};d=null;val q=p;p=null;runCatching{q?.stop()};if(Build.VERSION.SDK_INT>=29)u?.let{contentResolver.update(it,ContentValues().apply{put(MediaStore.Downloads.IS_PENDING,0)},null,null)};lastName=currentName;lastUri=currentUri;lastStartedAt=currentStartedAt;currentName="";currentUri="";currentStartedAt=0L;stopForeground(STOP_FOREGROUND_REMOVE);stopSelf()}
 override fun onDestroy(){if(isRecording)stopRec();super.onDestroy()}
 private fun safe(s:String)=s.replace(Regex("[\\\\/:*?\"<>|\\r\\n]+"),"_").replace(Regex("\\s+"),"_").trim('_').take(80)
 companion object{const val START="com.example.celltracker.TEST_RECORD_START";const val STOP="com.example.celltracker.TEST_RECORD_STOP";const val CODE="code";const val DATA="data";const val NAME="name";const val CH="celltracker_test_record";const val NID=1011;@Volatile var isRecording=false;@Volatile var currentName="";@Volatile var currentUri="";@Volatile var lastName="";@Volatile var lastUri="";@Volatile var currentStartedAt=0L;@Volatile var lastStartedAt=0L}
}