package com.example.celltracker

import android.content.*
import android.os.*
import android.provider.MediaStore
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object VideoLoadingExporter{
 fun export(c:Context,path:String):ExportResult{val d=VideoLoadingRepository(c).load(path);val src=File(path);val base=src.nameWithoutExtension;val csv=save(c,src.name,"text/csv",src.readBytes()).toString();val htmlName="${base}_summary.html";val html=save(c,htmlName,"text/html",html(d).toByteArray()).toString();val xlsxName="${base}_report.xlsx";val rows=src.readLines().filter{it.isNotBlank()}.map{parse(it)};val ok=d.samples.mapNotNull{it.delayMs}.sorted();fun p(x:Double)=ok.takeIf{it.isNotEmpty()}?.get(kotlin.math.ceil((it.size-1)*x).toInt().coerceIn(0,it.lastIndex));val summary=listOf(listOf("CellTracker YouTube Video Page Loading"),listOf("Status",d.status),listOf("Attempts",d.samples.size.toString()),listOf("Success",d.samples.count{it.result=="PASS"}.toString()),listOf("Timeout",d.samples.count{it.result=="TIMEOUT"}.toString()),listOf("Average ms",ok.takeIf{it.isNotEmpty()}?.average()?.toString().orEmpty()),listOf("Median ms",p(.5)?.toString().orEmpty()),listOf("P90 ms",p(.9)?.toString().orEmpty()),listOf("P95 ms",p(.95)?.toString().orEmpty()),listOf("Min ms",ok.minOrNull()?.toString().orEmpty()),listOf("Max ms",ok.maxOrNull()?.toString().orEmpty()),listOf("Recording Path",d.recordingPath.orEmpty()));val xlsx=PingExporter.simpleXlsx(listOf("Summary" to summary,"Video Loading" to rows));val xu=save(c,xlsxName,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",xlsx).toString();return ExportResult("YouTube Video Loading report exported · HTML + Excel + CSV",listOf(csv),html,htmlName,xu,xlsxName)}
 private fun html(d:VideoLoadingDetail):String{val v=d.samples.mapNotNull{it.delayMs}.sorted();fun p(x:Double)=v.takeIf{it.isNotEmpty()}?.get(kotlin.math.ceil((it.size-1)*x).toInt().coerceIn(0,it.lastIndex));fun e(s:String)=s.replace("&","&amp;").replace("<","&lt;");return buildString{append("<html><head><meta name='viewport' content='width=device-width'><style>body{font-family:sans-serif;margin:18px}table{border-collapse:collapse;width:100%;display:block;overflow:auto}td,th{padding:8px;border-bottom:1px solid #ddd;white-space:nowrap}.card{padding:12px;border:1px solid #ddd;border-radius:12px;margin:10px 0}</style></head><body><h1>YouTube Video Page Loading</h1>");append("<div class='card'>Attempts ${d.samples.size} · Success ${d.samples.count{it.result=="PASS"}} · Timeout ${d.samples.count{it.result=="TIMEOUT"}}<br>Average ${v.takeIf{it.isNotEmpty()}?.average()?.let{String.format(Locale.US,"%.0f ms",it)}?:"--"} · P90 ${p(.9)?:"--"} ms · P95 ${p(.95)?:"--"} ms</div><table><tr><th>#</th><th>Title</th><th>Delay</th><th>Result</th><th>Detection</th><th>RAT</th><th>RSRP</th><th>SINR</th><th>PCI</th></tr>");d.samples.forEach{append("<tr><td>${it.sequence}</td><td>${e(it.title)}</td><td>${it.delayMs?:"--"} ms</td><td>${it.result}</td><td>${it.detection}</td><td>${e(it.snapshot.displayRat)}</td><td>${e(it.snapshot.rsrp)}</td><td>${e(it.snapshot.sinr)}</td><td>${e(it.snapshot.pci)}</td></tr>")};append("</table></body></html>")}}
 private fun save(c:Context,n:String,m:String,b:ByteArray):android.net.Uri{if(Build.VERSION.SDK_INT>=29){val cv=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,n);put(MediaStore.Downloads.MIME_TYPE,m);put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/CellTracker")};val u=c.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv)!!;c.contentResolver.openOutputStream(u)!!.use{it.write(b)};return u};throw IllegalStateException("Android 10+ required")}
 private fun parse(s:String):List<String>{val o=mutableListOf<String>();val b=StringBuilder();var q=false;var i=0;while(i<s.length){val c=s[i];if(c=='\"'&&q&&i+1<s.length&&s[i+1]=='\"'){b.append('\"');i++}else if(c=='\"')q=!q else if(c==','&&!q){o+=b.toString();b.setLength(0)}else b.append(c);i++};o+=b.toString();return o}
}
