package com.example.celltracker

import android.accessibilityservice.AccessibilityService
import android.content.*
import android.graphics.PixelFormat
import android.os.*
import android.provider.Settings
import android.view.*
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo
import android.widget.*
import androidx.core.content.ContextCompat
import kotlinx.coroutines.*
import java.io.File

class YouTubeLoadingAccessibilityService:AccessibilityService(){
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Main);private lateinit var repo:VideoLoadingRepository;private var overlay:View?=null;private var file:File?=null;private var config=VideoLoadingConfig();private var running=false;private var seq=0;private var t0=0L;private var currentTitle="";private var recordingStarted=false
 override fun onServiceConnected(){repo=VideoLoadingRepository(this);config=repo.loadConfig();if(repo.isArmed())showOverlay()}
 override fun onAccessibilityEvent(e:AccessibilityEvent?){if(repo.isArmed()&&overlay==null)showOverlay()}
 override fun onInterrupt(){}
 override fun onDestroy(){scope.cancel();super.onDestroy()}
 private fun showOverlay(){if(overlay!=null)return;val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,14,20,14);setBackgroundColor(0xDD202124.toInt())};val status=TextView(this).apply{setTextColor(0xffffffff.toInt());text="YouTube Video Test · Ready"};val row=LinearLayout(this);val start=Button(this).apply{text="START"};val loaded=Button(this).apply{text="LOADED";visibility=View.GONE};val stop=Button(this).apply{text="STOP";visibility=View.GONE};row.addView(start);row.addView(loaded);row.addView(stop);box.addView(status);box.addView(row);start.setOnClickListener{start.visibility=View.GONE;loaded.visibility=View.VISIBLE;stop.visibility=View.VISIBLE;startTest(status)};loaded.setOnClickListener{if(running&&t0>0)completeAttempt("PASS","MANUAL",status)};stop.setOnClickListener{stopTest("Stopped",status)};val lp=WindowManager.LayoutParams(WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT).apply{gravity=Gravity.TOP or Gravity.END;x=16;y=160};getSystemService(WindowManager::class.java).addView(box,lp);overlay=box}
 private fun startTest(status:TextView){if(packageName==rootInActiveWindow?.packageName){status.text="Open YouTube channel Videos page first";return};config=repo.loadConfig();val now=System.currentTimeMillis();file=repo.create(now);running=true;seq=0;if(config.autoRecord&&!RecordingState.status.value.isRecording){val sub=android.telephony.SubscriptionManager.getDefaultDataSubscriptionId();ContextCompat.startForegroundService(this,Intent(this,RecordingService::class.java).putExtra(RecordingService.EXTRA_SUBSCRIPTION_ID,sub).putExtra(RecordingService.EXTRA_TASK_NAME,"YouTube_Video_Loading"));recordingStarted=true};scope.launch{delay(500);next(status)}}
 private suspend fun next(status:TextView){if(!running)return;if(seq>=config.count){stopTest("Completed",status);return};if(rootInActiveWindow?.packageName?.toString()!="com.google.android.youtube"){status.text="Please return to YouTube channel Videos page";return};delay(config.returnWaitMs);val candidates=videoCandidates(rootInActiveWindow);if(candidates.isEmpty()){status.text="No video item found · scroll channel Videos list";return};val node=candidates.getOrNull(seq.coerceAtMost(candidates.lastIndex))?:candidates.last();currentTitle=(node.contentDescription?:node.text?:"Video ${seq+1}").toString().take(160);seq++;t0=System.currentTimeMillis();status.text="Video $seq/${config.count} · Loading…";node.performAction(AccessibilityNodeInfo.ACTION_CLICK);scope.launch{val thisSeq=seq;delay(900);var stableHits=0;while(running&&seq==thisSeq&&System.currentTimeMillis()-t0<config.timeoutMs){delay(300);if(isVideoPageReady(rootInActiveWindow))stableHits++ else stableHits=0;if(stableHits>=3){completeAttempt("PASS","AUTO",status);return@launch}};if(running&&seq==thisSeq&&t0>0)completeAttempt("TIMEOUT","AUTO",status)}}
 private fun completeAttempt(result:String,detection:String,status:TextView){val start=t0;if(start<=0)return;t0=0;scope.launch{val now=System.currentTimeMillis();val snap=withContext(Dispatchers.IO){snapshot()};repo.append(file!!,VideoLoadingSample(seq,currentTitle,start,if(result=="PASS")now else 0,if(result=="PASS")now-start else null,result,detection,snap));status.text="Video $seq · ${if(result=="PASS")"${now-start} ms" else "TIMEOUT"}";performGlobalAction(GLOBAL_ACTION_BACK);delay(config.returnWaitMs);next(status)}}
 private fun stopTest(state:String,status:TextView){if(!running&&file==null)return;running=false;t0=0;val f=file;file=null;if(f!=null)repo.finish(f,0,System.currentTimeMillis(),state,RecordingState.status.value.path);if(recordingStarted){stopService(Intent(this,RecordingService::class.java));recordingStarted=false};repo.disarm();status.text="YouTube Test · $state"}
 private fun videoCandidates(root:AccessibilityNodeInfo?):List<AccessibilityNodeInfo>{val out=mutableListOf<AccessibilityNodeInfo>();walk(root){n->val d=(n.contentDescription?:"").toString();val t=(n.text?:"").toString();if(n.isClickable&&(d.length>5||t.length>5)&&!d.contains("tab",true)&&!d.contains("button",true))out+=n};return out.distinctBy{it.hashCode()}.take(30)}
 private fun isVideoPageReady(root:AccessibilityNodeInfo?):Boolean{if(root==null||root.packageName?.toString()!="com.google.android.youtube")return false;var player=false;var actions=0;var loading=false;walk(root){n->val s=((n.text?:"").toString()+" "+(n.contentDescription?:"").toString()).lowercase();if("pause" in s||"play video" in s||"video player" in s)player=true;if("like" in s||"share" in s||"comment" in s||"subscribe" in s)actions++;if("loading" in s||"progress" in s)loading=true};return player&&actions>=2&&!loading}
 private fun walk(n:AccessibilityNodeInfo?,f:(AccessibilityNodeInfo)->Unit){if(n==null)return;f(n);for(i in 0 until n.childCount)walk(n.getChild(i),f)}
 private suspend fun snapshot():PingNetworkSnapshot{val sims=runCatching{CellularRepository(this).readAllSims()}.getOrDefault(emptyList());val id=android.telephony.SubscriptionManager.getDefaultDataSubscriptionId();val s=sims.firstOrNull{it.subscriptionId==id}?:sims.firstOrNull();val c=s?.servingCell;val l=LocationStore.latest.value;return PingNetworkSnapshot(subscriptionId=s?.subscriptionId?:-1,simSlot=s?.simSlotIndex?:-1,operator=c?.operator?:"--",rat=c?.rat?:"--",displayRat=c?.displayRat?:"--",rsrp=c?.rsrp?:"--",rsrq=c?.rsrq?:"--",sinr=c?.sinr?:"--",rssi=c?.rssi?:"--",band=c?.band?:"--",pci=c?.pci?:"--",arfcn=c?.arfcn?:"--",latitude=l.latitude.toDoubleOrNull(),longitude=l.longitude.toDoubleOrNull())}
}
